apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::379297702835:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KE7WLN8L5RT1
      username: system:node:{{EC2PrivateDNSName}}
      - rolearn: arn:aws:iam::379297702835:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters  
        rolearn: arn:aws:iam::379297702835:role/UdacityFlaskDeployCBKubectlRole
        username: build            
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-03T10:03:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1243"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 34962611-eaa9-4f15-addc-6eb1d0a5b5db
